# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'FlussonicWatcherSample' do
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'IQKeyboardManager'
  pod 'DynamicMobileVLCKit', :tag => '3.3.0', :git => 'https://github.com/flussonic/DynamicMobileVLCKit.git'
  pod 'TrueTime', '~> 5.0.0'
  pod 'flussonic-watcher-sdk-ios', :tag => '1.5.3', :git => 'https://github.com/flussonic/flussonic-watcher-sdk-ios.git'

end
