# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlussonicWatcherSample' do
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'IQKeyboardManager'
  # required dependency for flussonic-watcher-sdk-ios
  pod 'DynamicMobileVLCKit', :http => 'https://flussonic-watcher-mobile-sdk.s3.eu-central-1.amazonaws.com/ios/DynamicMobileVLCKit/release/3.3.0/DynamicMobileVLCKit.zip'  
  pod 'flussonic-watcher-sdk-ios', :http => 'https://flussonic-watcher-mobile-sdk.s3.eu-central-1.amazonaws.com/ios/watcher-sdk/release/1.5.6/FlussonicSDK.zip'

  use_frameworks!

  # Pods for ErlyVideo

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
