// Generated by Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FlussonicSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSBundle;
@class NSCoder;

/// Class provides way to define date and time
SWIFT_CLASS("_TtC12FlussonicSDK22DateTimeViewController")
@interface DateTimeViewController : UIViewController
/// :nodoc:
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// Protocol describes public FlussonicBufferingListener methods
/// Used to notify delegate about buffering events
SWIFT_PROTOCOL_NAMED("FlussonicBufferingListener")
@protocol FlussonicBufferingListener
/// Called when buffering label shows
- (void)onBufferingStart;
/// Called when buffering label hides
- (void)onBufferingStop;
@end


/// Protocol describes public FlussonicDownloadRequestListener methods
/// Used to notify delegate about download request events
SWIFT_PROTOCOL_NAMED("FlussonicDownloadRequestListener")
@protocol FlussonicDownloadRequestListener
/// Called when user touches floppy disc button, requesting to download a part of the archive
/// SDK does not provide any functionality to download a part of the archive
/// \param from range start in seconds, unixtime
///
/// \param to range end in seconds, unixtime
///
- (void)onDownloadRequestFrom:(int64_t)from to:(int64_t)to;
@end


/// Protocol describes public FlussonicPlayerErrorListener methods
/// Used to receive information about errors occurred in player while playing
/// <ul>
///   <li>
///     some stream or while.
///   </li>
/// </ul>
SWIFT_PROTOCOL_NAMED("FlussonicPlayerErrorListener")
@protocol FlussonicDownloadRequestListener
/// Called if an error occurred in the player.
/// \param code code of error - response code, that received while starting playback with new url
///
/// \param message message of Error
///
/// \param url URL of stream provided in
///
- (void)onPlayerErrorWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message url:(NSString * _Nonnull)url;
@end

@class ProgressEvent;

/// Protocol describes public FlussonicUpdateProgressEventListener methods
/// Used to notify delegate about update progress events
SWIFT_PROTOCOL_NAMED("FlussonicUpdateProgressEventListener")
@protocol FlussonicUpdateProgressEventListener
/// Called on update progress event
- (void)onUpdateProgressWithEvent:(ProgressEvent * _Nonnull)event;
@end


/// Protocol describes public FlussonicWatcherDelegateProtocol methods
/// Used to notify delegate about toolbar expand/collapse events
SWIFT_PROTOCOL_NAMED("FlussonicWatcherDelegateProtocol")
@protocol FlussonicWatcherDelegateProtocol
/// Called when bottom toolbar starts to expand
- (void)expandToolbar;
/// Called when bottom toolbar starts to collapse
- (void)collapseToolbar;
/// Called when bottom toolbar shows without animation
- (void)showToolbar;
/// Called when bottom toolbar hides without animation
- (void)hideToolbar;
@end


/// Presents single camera view player and controls
/// note:
/// Camera view will try to take all possible screen space
/// note:
/// Can support up to 4 simultaneous instances due to hardware restrictions - @TODO: проверить
/// <ul>
///   <li>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC12FlussonicSDK20FlussonicWatcherView")
@interface FlussonicWatcherView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// :nodoc:
- (void)layoutSubviews;
/// Sets availability of downloading a portion of video stream as a separate clip
/// \param allowDownload new setting value
///
- (void)setAllowDownloadWithAllowDownload:(BOOL)allowDownload;
/// Sets starting position
/// Instance of FlussonicWatcherView will try to start playing from this position, if possible
/// \param dateTimeInSecs position to start, Unixtime
///
- (void)setStartPositionWithDateTimeInSecs:(int64_t)dateTimeInSecs;
/// Pauses current stream
- (void)pause;
/// Resumes current stream
/// note:
/// Live will jump to live, archive will resume from the current point
- (void)resume;
/// Tries to play from given time
/// \param seconds value to go to, Unixtime
///
- (void)seekWithSeconds:(NSTimeInterval)seconds;
/// Capture screenshot for the current stream
/// \param destUrl URL to save image to
///
- (void)captureScreenshotWithDestUrl:(NSURL * _Nonnull)destUrl;
@end



@class UIScrollView;

@interface FlussonicWatcherView (SWIFT_EXTENSION(FlussonicSDK)) <UIScrollViewDelegate>
- (UIView * _Nullable)viewForZoomingInScrollView:(UIScrollView * _Nonnull)scrollView SWIFT_WARN_UNUSED_RESULT;
/// :nodoc:
- (void)scrollViewDidZoom:(UIScrollView * _Nonnull)scrollView;
@end










/// Loads single frame clip and shows decoded image as a preview
/// note:
/// Loaded images will be cached, using URL as a key
/// note:
/// Will show “Broken camera” image if error
SWIFT_CLASS("_TtC12FlussonicSDK14PreviewMp4View")
@interface PreviewMp4View : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// Configure view with URL
/// note:
/// Loading will start immediately
/// note:
/// Successfully loaded image will be cached, using URL as a key
/// \param url either URL with user session as (protocol)://(session)@(server):(port)/(camera_name)/preview.mp4 or URL with camera token as (protocol)://(server):(port)/(camera_name)/preview.mp4?token=(camera_token)
///
- (void)withUrl:(NSURL * _Nonnull)url cacheKey:(NSString * _Nullable)cacheKey;
/// Reset preview view if reused
/// note:
/// Loading will not be cancelled, and image will be cached if loaded successfully
- (void)reset;
/// Clears the all previews cache
/// note:
/// Loading will not be cancelled, and image will be cached if loaded successfully
- (void)cleanCache;
/// Clears cache of url previews
/// note:
/// Loading will not be cancelled, and image will be cached if loaded successfully
- (void)cleanCacheForKey:(NSString * _Nonnull)cacheKey;
- (void)layoutSubviews;
@end


/// Protocol describes public PreviewMp4ViewStatusListener methods
/// Used to notify delegate about PreviewMp4View status events
/// *
SWIFT_PROTOCOL_NAMED("PreviewMp4ViewStatusListener")
@protocol PreviewMp4ViewStatusListener
/// Function called on status change
/// \param status new status
///
/// \param code error code or 0 if no error
///
/// \param message error message or “” in no error
///
- (void)onStatusChanged:(int8_t)status :(NSString * _Nonnull)code :(NSString * _Nonnull)message;
@end


/// Class is used to notify delegate about update progress events
SWIFT_CLASS("_TtC12FlussonicSDK13ProgressEvent")
@interface ProgressEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end













#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
